-- Databricks notebook source
-- COMMAND ----------
-- DBTITLE 1,Documentação do Processo de Pipeline de Dados
-- Este notebook documenta o fluxo completo do pipeline de dados
-- desde a ingestão até a camada gold

-- COMMAND ----------
-- DBTITLE 1,Visão Geral do Processo
-- O pipeline de dados é dividido em 3 camadas principais:
--
-- 1. SOURCE TO BRONZE (Ingestão)
--    - 3 ingestões de dados:
--      * ingestion_claim.sql: Ingestão de dados de claims
--      * ingestion_customers.sql: Ingestão de dados de customers
--      * ingestion_policies.sql: Ingestão de dados de policies
--    - Dados são carregados do volume para tabelas na camada bronze
--    - Formato: CSV
--    - Destino: ${catalog}.${schema_bronze}
--
-- 2. BRONZE TO SILVER (Transformação e Enriquecimento)
--    - 01_deduplicate_claims.sql: Deduplicação de claims
--      * Remove duplicatas mantendo apenas o registro mais recente por claim_no
--      * Usa ROW_NUMBER() com PARTITION BY claim_no ORDER BY claim_date DESC
--      * Cria tabela: claims_dedup
--    
--    - 02_join_tables_create.sql: Join de tabelas
--      * Combina claims_dedup com policies e customers
--      * Cria tabela enriquecida: claims_enriched
--      * Inclui informações de políticas e clientes
--
-- 3. SILVER TO GOLD (Métricas e Agregações)
--    - 03_join_tables_metrics.sql: Cálculo de métricas
--      * Gera métricas agregadas da tabela claims_enriched
--      * Conta registros, claims únicos, policies únicas, customers únicos

-- COMMAND ----------
-- DBTITLE 1,Diagrama do Fluxo do Processo
-- MAGIC %md
-- MAGIC ```mermaid
-- MAGIC graph TD
-- MAGIC     A[Volume Landing Zone<br/>CSV Files] --> B1[Ingestão Claims<br/>ingestion_claim.sql]
-- MAGIC     A --> B2[Ingestão Customers<br/>ingestion_customers.sql]
-- MAGIC     A --> B3[Ingestão Policies<br/>ingestion_policies.sql]
-- MAGIC     
-- MAGIC     B1 --> C1[Bronze: claims]
-- MAGIC     B2 --> C2[Bronze: customers]
-- MAGIC     B3 --> C3[Bronze: policies]
-- MAGIC     
-- MAGIC     C1 --> D[Deduplicação<br/>01_deduplicate_claims.sql]
-- MAGIC     D --> E[Silver: claims_dedup]
-- MAGIC     
-- MAGIC     E --> F[Join de Tabelas<br/>02_join_tables_create.sql]
-- MAGIC     C2 --> F
-- MAGIC     C3 --> F
-- MAGIC     
-- MAGIC     F --> G[Silver: claims_enriched]
-- MAGIC     
-- MAGIC     G --> H[Cálculo de Métricas<br/>03_join_tables_metrics.sql]
-- MAGIC     H --> I[Gold: Métricas]
-- MAGIC     
-- MAGIC     style A fill:#e1f5ff
-- MAGIC     style C1 fill:#fff4e1
-- MAGIC     style C2 fill:#fff4e1
-- MAGIC     style C3 fill:#fff4e1
-- MAGIC     style E fill:#e8f5e9
-- MAGIC     style G fill:#e8f5e9
-- MAGIC     style I fill:#f3e5f5
-- MAGIC ```

-- COMMAND ----------
-- DBTITLE 1,Detalhamento das Etapas

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ### Etapa 1: Source to Bronze (Ingestão)
-- MAGIC 
-- MAGIC **Objetivo**: Carregar dados brutos do volume para a camada bronze
-- MAGIC 
-- MAGIC **Notebooks**:
-- MAGIC - `source_to_bronze/ingestion_claim.sql`
-- MAGIC - `source_to_bronze/ingestion_customers.sql`
-- MAGIC - `source_to_bronze/ingestion_policies.sql`
-- MAGIC 
-- MAGIC **Características**:
-- MAGIC - Processa arquivos CSV do volume `/Volumes/${catalog}/00_landing/sql_server/`
-- MAGIC - Usa `read_files()` para leitura dos arquivos
-- MAGIC - Cria tabelas na camada bronze sem transformações
-- MAGIC - Permite reprocessamento completo (DROP TABLE IF EXISTS)

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ### Etapa 2: Bronze to Silver (Transformação)
-- MAGIC 
-- MAGIC **Objetivo**: Limpar, deduplicar e enriquecer os dados
-- MAGIC 
-- MAGIC **2.1 Deduplicação** (`01_deduplicate_claims.sql`):
-- MAGIC - Remove duplicatas da tabela claims
-- MAGIC - Mantém apenas o registro mais recente por `claim_no`
-- MAGIC - Ordena por `claim_date DESC NULLS LAST`
-- MAGIC - Cria tabela `claims_dedup` na camada silver
-- MAGIC 
-- MAGIC **2.2 Join de Tabelas** (`02_join_tables_create.sql`):
-- MAGIC - Combina `claims_dedup` com `policies` e `customers`
-- MAGIC - Realiza INNER JOINs para enriquecer os dados
-- MAGIC - Cria tabela `claims_enriched` com todas as informações consolidadas
-- MAGIC - Adiciona timestamp `processed_at` para rastreabilidade

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ### Etapa 3: Silver to Gold (Métricas)
-- MAGIC 
-- MAGIC **Objetivo**: Calcular métricas e agregações para análise
-- MAGIC 
-- MAGIC **Notebook**: `silver_to_gold/03_join_tables_metrics.sql`
-- MAGIC 
-- MAGIC **Métricas calculadas**:
-- MAGIC - Total de registros enriquecidos
-- MAGIC - Número de claims únicos
-- MAGIC - Número de policies únicas
-- MAGIC - Número de customers únicos
-- MAGIC - Mensagem de conclusão do processo

-- COMMAND ----------
-- DBTITLE 1,Variáveis Utilizadas
-- MAGIC %md
-- MAGIC ### Variáveis de Ambiente/Task
-- MAGIC 
-- MAGIC O pipeline utiliza as seguintes variáveis que devem ser configuradas:
-- MAGIC 
-- MAGIC - `${catalog}`: Nome do catálogo (ex: smart_claims_dev)
-- MAGIC - `${schema_bronze}`: Nome do schema bronze (ex: 01_bronze)
-- MAGIC - `${schema_silver}`: Nome do schema silver (ex: 02_silver)
-- MAGIC - `${schema_gold}`: Nome do schema gold (ex: 03_gold)
-- MAGIC 
-- MAGIC Essas variáveis podem ser definidas via:
-- MAGIC - Widgets do Databricks (`dbutils.widgets`)
-- MAGIC - Variáveis de ambiente
-- MAGIC - Parâmetros de Jobs/Tasks do Databricks Workflows

-- COMMAND ----------
-- DBTITLE 1,Ordem de Execução Recomendada
-- MAGIC %md
-- MAGIC ### Sequência de Execução
-- MAGIC 
-- MAGIC 1. **Ingestão (Source to Bronze)**
-- MAGIC    - Executar `ingestion_claim.sql`
-- MAGIC    - Executar `ingestion_customers.sql`
-- MAGIC    - Executar `ingestion_policies.sql`
-- MAGIC    - *Ordem pode ser paralela, mas todas devem completar antes do próximo passo*
-- MAGIC 
-- MAGIC 2. **Transformação (Bronze to Silver)**
-- MAGIC    - Executar `01_deduplicate_claims.sql` (depende de bronze.claims)
-- MAGIC    - Executar `02_join_tables_create.sql` (depende de claims_dedup, policies, customers)
-- MAGIC 
-- MAGIC 3. **Métricas (Silver to Gold)**
-- MAGIC    - Executar `silver_to_gold/03_join_tables_metrics.sql` (depende de claims_enriched)
-- MAGIC 
-- MAGIC **Nota**: Esta sequência pode ser automatizada usando Databricks Workflows com dependências entre tasks.

